### ISSUE TITLE
Different linter config file

### ISSUE THREAD

**Issue by bolah2009** [adriaanbd/reagir_calculator#9]
Can we use the recommend config file (https://github.com/microverseinc/linters-config/blob/d360178d194951797c9151e768d2e21e089e1a3c/react-redux/.eslintrc.json) instead?

Few things to note about the current config file:
- It doesn't have the `"jest": true` in the `env` property hence the test is failing for some `jest` terms when this rule is removed `"no-undef": "off"`. 
- There are many redundant rules been disabled unnecessarily, rules like "no-console", "no-use-before-define", "no-param-reassign", "no-undef", "no-unused-vars" shouldn't be disabled.

https://github.com/adriaanbd/reagir_calculator/blob/8e4c04030ab596c5818d2a859c6161001e70d731/.eslintrc.json#L1-L38

**Comment by adriaanbd** [comment]
That's the one I'm using. I've disabled some of those rules because if I didn't then Stickler would have complained by meeting Microverse requirements. For example, Milestone 4 requires us to import the calculate function into App even though we aren't using that function, and eslit/stickler would have yelled at that and my PR would have been pushed back for meeting a Microverse requirement.

**Comment by adriaanbd** [comment]
Where is it set to "jest": true? I don't see that.

**Comment by adriaanbd** [comment]
It's fixed now, thank you!
